# Generated by Django 4.2.28 on 2026-02-24 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(help_text='Örn: Ziraat Bankası Visa', max_length=100, verbose_name='Kart Adı')),
                ('last_four', models.CharField(max_length=4, verbose_name='Son 4 Hane')),
                ('card_color', models.CharField(default='#6366f1', help_text='HEX renk kodu (örn: #6366f1)', max_length=7, verbose_name='Kart Rengi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kredi Kartı',
                'verbose_name_plural': 'Kredi Kartları',
                'ordering': ['card_name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Abonelik Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ücret (₺)')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Aylık'), ('yearly', 'Yıllık')], default='monthly', max_length=10, verbose_name='Ödeme Periyodu')),
                ('renewal_date', models.DateField(verbose_name='Sonraki Ödeme Tarihi')),
                ('category', models.CharField(choices=[('muzik', 'Müzik'), ('video', 'Video & Streaming'), ('oyun', 'Oyun'), ('bulut', 'Bulut Depolama'), ('yazilim', 'Yazılım'), ('egitim', 'Eğitim'), ('haber', 'Haber & Dergi'), ('saglik', 'Sağlık & Fitness'), ('diger', 'Diğer')], default='diger', max_length=20, verbose_name='Kategori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.creditcard', verbose_name='Kredi Kartı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonelik',
                'verbose_name_plural': 'Abonelikler',
                'ordering': ['renewal_date'],
            },
        ),
    ]
