# Generated by Django 4.2.28 on 2026-05-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateField(blank=True, null=True, verbose_name='İptal Tarihi'),
        ),
    ]
